### PR TITLE
feat: add filtering options to svelteJsxSnippet plugin

### PR DESCRIPTION
**Pull request by ryoppippi**
Hi
I added an option to change include/exclude filter for vite plugin!

### CODE REVIEW

**Comment by ssssota** [comment]
@ryoppippi Thanks for your contribution! Please format with `pnpm fmt`.

**Comment by ryoppippi** [comment]
@ssssota Hi! I ran the fmt command!

**Comment by ssssota** [comment]
`@rollup/pluginutils` の中で使ってるpicomatchがCJSで `require("path")` しているせいでビルドに失敗していそう

**Comment by ssssota** [comment]
I think we should move @rollup/pluginutils from devDependencies to the dependencies field

**Comment by ryoppippi** [comment]
maybe we can add some options to tsconfig.json

**Comment by ryoppippi** [comment]
I just move rollup/utils to the dependency and it works as you said

**Comment by ssssota** [comment]
We did it! Thank you!

**Pull request merged**
